# Generated by Django 3.0.5 on 2020-04-16 23:54

from django.db import migrations
import userAccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', userAccount.models.MyAccountManager()),
            ],
        ),
    ]
