# Generated by Django 3.0.5 on 2020-04-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='home_city',
            new_name='city',
        ),
    ]
