# Generated by Django 3.0.5 on 2020-04-25 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('messageDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Requested')),
                ('messageText', models.TextField(default='Message Body', max_length=10000)),
            ],
        ),
    ]
