# Generated by Django 3.0.5 on 2020-04-25 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0006_remove_job_contractornotes'),
        ('contractor', '0004_auto_20200421_2154'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('messageDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Requested')),
                ('messageText', models.TextField(default='Message Body', max_length=10000)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('contractorID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractor.Contractor')),
                ('jobID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.Job')),
            ],
        ),
    ]
