# Generated by Django 3.0.5 on 2020-04-25 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractor', '0002_contractor_skill'),
        ('message', '0001_initial'),
        ('job', '0002_auto_20200425_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='clientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='contractorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractor.Contractor'),
        ),
        migrations.AddField(
            model_name='message',
            name='jobID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.Job'),
        ),
    ]
