# Generated by Django 3.0.5 on 2020-04-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0003_auto_20200425_1456'),
        ('message', '0002_auto_20200425_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contractorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractor.Contractor', to_field='email'),
        ),
    ]
