# Generated by Django 3.0.5 on 2020-04-25 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAccount', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skillType', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(default=None, max_length=50, null=True)),
                ('city', models.ManyToManyField(to='contractor.City', verbose_name='Available Cities')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('skill', models.ManyToManyField(to='contractor.Skill')),
            ],
        ),
    ]
