# Generated by Django 3.0.5 on 2020-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='city',
        ),
        migrations.AddField(
            model_name='contractor',
            name='city',
            field=models.ManyToManyField(to='contractor.City'),
        ),
    ]
