# Generated by Django 3.0.5 on 2020-04-21 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractor', '0002_contractor_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='company_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
