# Generated by Django 3.0.5 on 2020-04-25 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractor', '0003_auto_20200425_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
