# Generated by Django 3.0.5 on 2020-04-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0003_auto_20200421_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='company_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
