# Generated by Django 3.0.5 on 2020-04-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientNotes', models.TextField(default='No details provided', max_length=10000)),
                ('dateRequested', models.DateTimeField(auto_now_add=True, verbose_name='Date Requested')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='requested', max_length=9)),
            ],
        ),
    ]
