# Generated by Django 3.0.5 on 2020-04-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20200423_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='dateRequested',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Requested'),
        ),
    ]
