# Generated by Django 3.0.5 on 2020-04-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200424_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='active',
        ),
        migrations.RemoveField(
            model_name='job',
            name='clientConfirmed',
        ),
        migrations.RemoveField(
            model_name='job',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='job',
            name='contractorAccepted',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='requested', max_length=9),
        ),
    ]
