# Generated by Django 3.0.5 on 2020-04-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20200424_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contractorNotes',
        ),
    ]
