# Generated by Django 3.0.4 on 2020-04-06 19:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_auto_20200406_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skillChoice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('el', 'Electrician'), ('pl', 'Plumber'), ('hk', 'Housekeeper')], default='el', max_length=8),
            preserve_default=False,
        ),
    ]
