# Generated by Django 3.0.4 on 2020-04-06 19:55

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_skills_skillchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='skills',
            field=models.ForeignKey(default='electrician', on_delete=django.db.models.deletion.CASCADE, to='contractors.Skills'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skillChoice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('housekeeper', 'Housekeeper')], max_length=31),
        ),
    ]
