# Generated by Django 3.0.4 on 2020-04-06 21:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0005_auto_20200406_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skillChoice',
        ),
        migrations.AlterField(
            model_name='contractor',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('housekeeper', 'Housekeeper')], default='housekeeper', max_length=31),
        ),
    ]
