# Generated by Django 3.0.4 on 2020-04-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0006_auto_20200406_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='skills',
        ),
        migrations.AddField(
            model_name='contractor',
            name='skills',
            field=models.ManyToManyField(default='housekeeper', to='contractors.Skills'),
        ),
    ]
