# Generated by Django 3.0.4 on 2020-04-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0007_auto_20200406_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillChoice', models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('housekeeper', 'Housekeeper')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.AlterField(
            model_name='contractor',
            name='skills',
            field=models.ManyToManyField(default='housekeeper', to='contractors.Skill'),
        ),
    ]
