# Generated by Django 3.0.4 on 2020-04-06 21:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0008_auto_20200406_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skillChoice',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='skills',
        ),
        migrations.AddField(
            model_name='contractor',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('housekeeper', 'Housekeeper')], default='housekeeper', max_length=31),
        ),
    ]
