# Generated by Django 3.0.4 on 2020-04-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0009_auto_20200406_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skillList',
            field=models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('housekeeper', 'Housekeeper')], max_length=100, null=True),
        ),
    ]
